### ISSUE TITLE
Container dies when reaches slack rate limit

### ISSUE THREAD

**Issue by yoku0825** [asayamakk/botbot#1]
Our container dies with following stacktrace.

```
I, [2018-01-10T16:01:25.205938 #5]  INFO -- : Issue is created, url: issue_url
/usr/local/bundle/gems/slack-api-1.6.0/lib/faraday/raise_http_exception.rb:17:in `block in call': POST https://slack.com/api/chat.postMessage: 503: Slack is rate limiting your requests. (Slack::ServiceUnavailable)
        from /usr/local/bundle/gems/faraday-0.13.1/lib/faraday/response.rb:61:in `on_complete'
        from /usr/local/bundle/gems/slack-api-1.6.0/lib/faraday/raise_http_exception.rb:8:in `call'
        from /usr/local/bundle/gems/faraday_middleware-0.10.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
        from /usr/local/bundle/gems/faraday-0.13.1/lib/faraday/request/url_encoded.rb:15:in `call'
        from /usr/local/bundle/gems/faraday-0.13.1/lib/faraday/request/multipart.rb:15:in `call'
        from /usr/local/bundle/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
        from /usr/local/bundle/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
        from /usr/local/bundle/gems/faraday-0.13.1/lib/faraday/connection.rb:174:in `post'
        from /usr/local/bundle/gems/slack-api-1.6.0/lib/slack/request.rb:29:in `request'
        from /usr/local/bundle/gems/slack-api-1.6.0/lib/slack/request.rb:11:in `post'
        from /usr/local/bundle/gems/slack-api-1.6.0/lib/slack/endpoint/chat.rb:76:in `chat_postMessage'
        from /home/bot/botbot/slack_handler.rb:21:in `post_message'
        from /home/bot/botbot/reactor.rb:39:in `react_to_message'
        from index.rb:24:in `block in <main>'
        from /usr/local/bundle/gems/slack-api-1.6.0/lib/slack/realtime/client.rb:29:in `block (3 levels) in start'
        from /usr/local/bundle/gems/slack-api-1.6.0/lib/slack/realtime/client.rb:28:in `each'
        from /usr/local/bundle/gems/slack-api-1.6.0/lib/slack/realtime/client.rb:28:in `block (2 levels) in start'
        from /usr/local/bundle/gems/websocket-driver-0.7.0/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
        from /usr/local/bundle/gems/websocket-driver-0.7.0/lib/websocket/driver/event_emitter.rb:38:in `each'
        from /usr/local/bundle/gems/websocket-driver-0.7.0/lib/websocket/driver/event_emitter.rb:38:in `emit'
        from /usr/local/bundle/gems/faye-websocket-0.10.7/lib/faye/websocket/api/event_target.rb:44:in `dispatch_event'
        from /usr/local/bundle/gems/faye-websocket-0.10.7/lib/faye/websocket/api.rb:113:in `receive_message'
        from /usr/local/bundle/gems/faye-websocket-0.10.7/lib/faye/websocket/api.rb:45:in `block in initialize'
        from /usr/local/bundle/gems/websocket-driver-0.7.0/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
        from /usr/local/bundle/gems/websocket-driver-0.7.0/lib/websocket/driver/event_emitter.rb:38:in `each'
        from /usr/local/bundle/gems/websocket-driver-0.7.0/lib/websocket/driver/event_emitter.rb:38:in `emit'
        from /usr/local/bundle/gems/websocket-driver-0.7.0/lib/websocket/driver/hybi.rb:398:in `emit_message'
        from /usr/local/bundle/gems/websocket-driver-0.7.0/lib/websocket/driver/hybi.rb:381:in `emit_frame'
        from /usr/local/bundle/gems/websocket-driver-0.7.0/lib/websocket/driver/hybi.rb:123:in `parse'
        from /usr/local/bundle/gems/websocket-driver-0.7.0/lib/websocket/driver/client.rb:63:in `parse'
        from /usr/local/bundle/gems/faye-websocket-0.10.7/lib/faye/websocket/api.rb:153:in `parse'
        from /usr/local/bundle/gems/faye-websocket-0.10.7/lib/faye/websocket/client.rb:80:in `receive_data'
        from /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
        from /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
        from /usr/local/bundle/gems/slack-api-1.6.0/lib/slack/realtime/client.rb:19:in `start'
        from index.rb:27:in `<main>'
```

**Comment by yoku0825** [comment]
I sent a PR #2

**Comment by asayamakk** [comment]
It has been fixed 🎉
